# docs: https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "nokogiri"
        versions: [">= 1.18"]
