#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Francesco Pira"

# Short bio or description (displayed in the header)
description: "Curious mind, Oracle Enterprise Application Developer Consultant and Computer Engineering student"

# Author
author:
  name: "Francesco Pira"
  email: ""

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "/assets/images/avatar.jpg"

# timezone
timezone: Europe/Rome

# locale setting
locale: en_US

# Your website URL (e.g. http://fpira.com)
# It's important to include http. If you use SSL, write https.
url: https://fpira.com

# Your website domain (without http:// and https://)
domain: fpira.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Define a separator to put between the page.title and site.name
title_separator: "&#183;"

# Theme Engine
# To change site-wide fonts and colors, go to _sass/_variables anche change the hex values.
theme_engine:
  primary_color: 3344aa
  secondary_color: 4183C4

# Analytics
# Enter your Google Analytics web tracking code (e.g. UA-1234567-1) to activate tracking
# Leave it empty to disable any of the settings.
analytics:
  google: "UA-59510020-2"
  matomo: "1"
  heatmap: yes

# Links to use in JSON-LD metadata (SEO)
seo_links:
  - "http://twitter.com/pirafrank"
  - "https://github.com/pirafrank"
  - "https://www.linkedin.com/in/fpira"
  - "http://plus.google.com/+FrancescoPiraonline"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# Leave it empty to disable
disqus:

# Choose whether to display social links in footer or not
footersocial: true

# Choose whether to display experimental features
experimental: false

# Home customisation
home:
  show_social: false # Choose whether to display social link in mid of home page or not
  max_posts: 5 # max number of latest posts to show in home page
  max_projects: 3 # max number of projects to show in the home page
  max_events: 3 # max number of entries from /events page to show in the home page
  show_excerpt: false # choose whether to show or not excerpt of latest blog posts
  show_pinboard: true # set it to true to enable, false to disable right section in home
  show_twitter_feed: false # NB. you have to REPLACE the code in home with the one for your twitter account.
  show_twitter_button: false # Choose whether to 'Follow me' button in home.

# Default values
# has_fa: enable font-awesome
# in_search: include in search. Posts are always included.
defaults:
  -
    scope:
      path: ""
    values:
      is_home: false
      has_fa: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"
      show_title: true
      in_search: true
      center: false
  -
    scope:
      path: "pages/projects"
      type: "pages"
    values:
      layout: "project"

# jekyll-archives settings
jekyll-archives:
  enabled:
    - categories
    - month
    - tags
  layout: 'archive'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tags/:name/'
    category: '/blog/categories/:name/'

#
# !! You don't need to change any of the configuration flags below !!
#

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block.line_numbers: true
highlighter: pygments
permalink: '/blog/:year/:month/:title/'
excerpt_separator: "\n\n"

# reading speed (avg.)
words_per_minute: 200

# Jekyll Blue version in use
version: v3.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # If you want to un-minify, set to :expanded

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist # Support for GitHub gists
  - jekyll-paginate # pagination support
  - jekyll-archives
  #- jekyll-minifier # compress html, css and js

# read default jekyll-minifier settings here:
# https://github.com/digitalsparky/jekyll-minifier
#jekyll-minifier:
#  exclude:
#    - 'feed.xml'
#    - 'sitemap.xml'
#    - '/**/*.min.js'
#    - '/**/*.min.css'
#    - '/**/*.min.map'
#    - 'humans.txt'
#    - 'robots.txt'
#    - 'search_data.json'
#    - 'manifest.json'
#    - 'service-worker.js'

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - deploy.sh
    - CONTRIBUTOR
    - sw-config.js
    - scripts
    - _jekyll_ignore
    - .gitignore
    - list_tags.sh
    - '/**/*.disabled'
