#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: "Francesco Pira"
author: "Francesco Pira"

# Short bio or description (displayed in the header)
description: "Curious mind, Web Developer, Computer Engineering student and CEO @ Fileshute"

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: "/assets/images/avatar.jpg"

# timezone
timezone: Europe/Rome

# Your website URL (e.g. http://fpira.com)
# It's important to include http. If you use SSL, write https.
url: https://fpira.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# ** The settings below are optional, but I recommend you to customize them. **
# Note: leaving a field empty disables that option.
#

# Theme Engine
# To change site-wide fonts and colors, go to _sass/_variables anche change the hex values.
theme_engine:
  primary_color: 34a
  secondary_color: 4183C4

# Enter your Google Analytics web tracking code (e.g. UA-1234567-1) to activate tracking
# Leave it empty to disable
google_analytics: ""

# Includes a social icon in social divs and make a link to that profile work for each username you enter
# Leave social links you don't have/use empty to disable them
social-links:
  dribbble:
  email:
  facebook:
  flickr: pirafrank
  github: pirafrank
  goodreads: pirafrank # your goodreads username, e.g. https://www.goodreads.com/johndoe
  googleplus: +FrancescoPiraonline # your username, including the plus char, e.g. https://plus.google.com/+johndoe
  instagram: pirafrank
  keybase: pirafrank # your keybase username
  lastfm: pirafrank
  linkedin: fpira
  medium: pirafrank # your medium username, e.g. https://medium.com/@johndoe
  packal: pirafrank # your packal.org username, e.g. https://www.packal.org/users/johndoe
  pinterest:
  pocket: pirafrank # your pocket username, e.g. https://getpocket.com/@johndoe
  reddit: pirafrank
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  skype: francesco-pira
  soundcloud: pirafrank
  slideshare: pirafrank # your slideshare username, http://www.slideshare.net/pirafrank
  stackoverflow: # your stackoverflow profile, e.g. "users/12345/john-doe"
  tumblr: pirafrank
  twitter: pirafrank
  youtube: # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
# Leave it empty to disable
disqus:

# Type your email with **1 space** between each character.
# Don't worry, it will be displayed correctly.
# For example: inbox@fpira.com -> i n b o x @ f p i r a . c o m
# NOTE: If you leave it empty, the link in About page won't work.
encryptedemail: "m e [ a t ] f p i r a [ d o t ] c o m"

# Write anything to enable search, leave it blank to disable
embedsearch: true

# Choose whether to display social links in footer or not
footersocial: true

# Home customisation
home:
  show_social: false # Choose whether to display social link in mid of home page or not
  max_posts: 6 # max number of latest posts to show in home page
  show_excerpt: false # choose whether to show or not excerpt of latest blog posts
  show_pinboard: true # set it to true to enable, false to disable right section in home
  show_twitter_feed: true # NB. you have to REPLACE the code in home with the one for your twitter account.

#
# !! You don't need to change any of the configuration flags below !!
#

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    block.line_numbers: true
highlighter: pygments
permalink: '/blog/:year/:month/:title/'
excerpt_separator: "\n\n"

# Jekyll Blue version in use
version: v3.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: compressed # If you want to un-minify, set to :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-gist # Support for GitHub gists
  # jekyll paginate removed as no longer under active development as of Jekyll 3

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - CNAME
    - LICENSE
    - README.md
    - deploy.sh
    - CONTRIBUTOR
