openapi: 3.0.3
info:
  title: fpira.com website and blog API
  description: API endpoints for blog posts, categories, tags and other site info
  version: 1.0.0
  termsOfService: https://fpira.com/terms
  license:
    name: GNU General Public License v3.0
    url: https://www.gnu.org/licenses/gpl-3.0.html

servers:
  - url: http://127.0.0.1:4001/api
    description: Development API server
  - url: https://fpira.com/api
    description: Production API server

paths:
  /v1/categories:
    get:
      operationId: v1CategoriesGet
      summary: 'Categories: Get all categories in the website'
      responses:
        200:
          description: List of website categories of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /v1/categories/{category_id}:
    get:
      operationId: v1CategoriesCategoryidGet
      summary: 'Categories: Get all posts for the given category in the website'
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of website posts in given category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /v1/ifttt/posts:
    get:
      operationId: v1IftttPosts
      summary: 'IFTTT: Get all posts in a format suitable for IFTTT'
      responses:
        200:
          description: List of all posts in IFTTT format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IftttObject'

  /v1/ifttt/posts/latest:
    get:
      operationId: v1IftttPostsLatest
      summary: 'IFTTT: Get latest post in a format suitable for IFTTT'
      responses:
        200:
          description: Latest post in IFTTT format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IftttObject'

  /v1/pages:
    get:
      operationId: v1PagesGet
      summary: 'Pages: Get all pages'
      responses:
        200:
          description: List of pages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Page'

  /v1/posts:
    get:
      operationId: v1PostsGet
      summary: 'Posts: Get all posts (sorted by last update date)'
      responses:
        200:
          description: Array of posts sorted by creation date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /v1/posts/latest:
    get:
      operationId: v1PostsLatestGet
      summary: 'Posts: Get latest blog post'
      responses:
        200:
          description: Latest (by creation date) post details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /v1/posts/by_update:
    get:
      operationId: v1PostsByUpdateGet
      summary: 'Posts: Get all posts (sorted by last update date)'
      responses:
        200:
          description: Array of posts sorted by update date
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /v1/posts/by_update/latest:
    get:
      operationId: v1PostsByUpdateLatestGet
      summary: 'Posts: Get latest blog post'
      responses:
        200:
          description: Latest (by update date) post details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'

  /v1/tags:
    get:
      operationId: v1TagsGet
      summary: 'Tags: Get all tags in the website'
      responses:
        200:
          description: List of website tags of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'

  /v1/tags/{tag_id}:
    get:
      operationId: v1TagsTagidGet
      summary: 'Tags: Get all posts for the given tag in the website'
      parameters:
        - name: tag_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of website posts having given tag
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'

  /v1/version:
    get:
      operationId: v1VersionGet
      summary: 'Version: Get website build info and version'
      responses:
        200:
          description: Build and version details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'

components:
  schemas:
    Type:
      type: string
      enum:
        - post
        - category
        - tag
        - page
    Page:
      type: object
      properties:
        type:
          type: string
          $ref: "#/components/schemas/Type"
        title:
          type: string
        id:
          type: string
        slug:
          type: string
        url:
          type: string
        path:
          type: string
    Post:
      type: object
      properties:
        type:
          type: string
          $ref: "#/components/schemas/Type"
        id:
          type: string
        postUrl:
          type: string
        title:
          type: string
        subtitle:
          type: string
        description:
          type: string
        published:
          type: string
          format: date-time
        lastUpdate:
          type: string
          format: date-time
        updates:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        seoImageUrl:
          type: string

    Category:
      type: object
      properties:
        type:
          type: string
          $ref: "#/components/schemas/Type"
        id:
          type: string
        name:
          type: string
        url:
          type: string
        count:
          type: integer

    Tag:
      type: object
      properties:
        type:
          type: string
          $ref: "#/components/schemas/Type"
        id:
          type: string
        name:
          type: string
        url:
          type: string
        count:
          type: integer

    Version:
      type: object
      properties:
        build:
          type: object
          properties:
            dateTime:
              type: string
              format: date-time
            jekyll:
              type: object
              properties:
                version:
                  type: string
                plugins:
                  type: array
                  items:
                    type: string
        lastCommit:
          type: object
          properties:
            hash:
              type: string
            url:
              type: string
            dateTime:
              type: string
              format: date-time
            branch:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
            tags:
              type: array
              items:
                type: string

    IftttObject:
      type: object
      properties:
        value1:
          type: string
        value2:
          type: string
        value3:
          type: string
