name: Deployment notification

on:
  deployment_status

jobs:
  notify:
    name: Notify deployment status
    runs-on: ubuntu-20.04
    # Continue only if some definitive status has been reported.
    if: github.event.deployment_status.state != 'pending'
    steps:
    - name: Send Push Notification
      uses: fjogeleit/http-request-action@master
      if: always()
      with:
        url: ${{ secrets.NOTIFICATION_WEBHOOK_URI }}
        method: 'POST'
        data: '{ "value1": "[GitHub] pirafrank/fpiracom", "value2": "Build of fpira.com (ref ${{ github.event.deployment.sha }}) finished with status ${{github.event.deployment_status.state}}", "value3": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
