name: 'Trigger Deploy on Vercel'

on:
  #schedule:
  #  - cron: '45 8 * * *'
  workflow_dispatch:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    outputs:
      RUN_BUILD: ${{ steps.check_new_posts.outputs.RUN_BUILD }}
    steps:
      - uses: actions/checkout@v2
      - name: Check for new blog posts
        id: check_new_posts
        shell: bash
        run: |
          # if run on schedule, check for new posts
          if [ ${GITHUB_EVENT_NAME} = 'schedule' ]; then
            if [ $(ls -1 _posts | grep $(date '+%Y-%m-%d')) ]; then
              echo "New posts found with today date"
              echo "::set-output name=RUN_BUILD::true"
            else
              echo "No new posts to publish with today date."
              echo "::set-output name=RUN_BUILD::false"
            fi
          else
            echo "No checks to perform, about to run build..."
            echo "::set-output name=RUN_BUILD::true"
          fi
  build:
    name: fpira.com vercel deploy
    runs-on: ubuntu-20.04
    needs: [checks]
    if: contains(needs.checks.outputs.RUN_BUILD, 'true')
    steps:
    - name: Deploy to vercel
      # deploy on vercel by triggering their webhook and letting them pull
      # and build the repo, instead of pushing as you'd do with vercel CLI.
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        method: 'POST'
