# .github/actions/git-info/action.yml

name: Git Info
description: Get current repository git info written to a JSON file
inputs:
  target_file:
    description: 'The file to write the git info to'
    required: true
runs:
  using: "composite"
  steps:
    - name: Git Info
      shell: bash
      env:
        TARGET_FILE: ${{ inputs.target_file }}
        ACTION_PATH: ${{ github.action_path }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        # prepend GITHUB_WORKSPACE if target_file is not an absolute path
        if [[ $TARGET_FILE != /* ]]; then
          TARGET_FILE="${GITHUB_WORKSPACE}/${TARGET_FILE}"
        fi
        bash ${ACTION_PATH}/git_info.sh > $TARGET_FILE
        echo "About to print the contents of $TARGET_FILE"
        cat $TARGET_FILE
