# .github/actions/setup-jekyll-env/action.yml

name: Setup Jekyll environment
description: Install Ruby, Bundler and Jekyll dependencies
runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
    - name: Cache ruby gems
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup Jekyll environment
      id: get_current_ref
      shell: bash
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}
      run: |
        cd $GITHUB_WORKSPACE
        BUNDLER_VERSION=$(grep 'BUNDLED WITH' -A1 Gemfile.lock | tail -n1 | awk '{print $1}')
        #sudo apt-get -yqq install libpq-dev
        #gem update --system
        gem install bundler -v ${BUNDLER_VERSION}
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
