name: 'Update Algolia Index'

on:
  #push:
  #  branches:
  #    - main
  #  paths:
  #    - "_posts"

  # edits to data needs a rebuild/republish of the website.
  # running index update makes sense only after website rebuild.
  workflow_run:
    workflows: [deploy on vercel]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Update Algolia index
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # always build from production branch
        ref: main
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Cache ruby gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup env
      shell: bash
      run: |
        #sudo apt-get -yqq install libpq-dev
        gem update --system
        gem install bundler:2.1.4
    - name: Install deps
      shell: bash
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Update Algolia Index
      shell: bash
      env:
        JEKYLL_ENV: production
        ALGOLIA_API_KEY: {{ secrets.ALGOLIA_API_KEY }}
      run: |
        #bundle exec jekyll build --trace
        bundle exec jekyll algolia

