
name: 'Check build'

on:
  # Note that GITHUB_SHA for this event is the last merge commit of the pull
  # request merge branch. If you want to get the commit ID for the last commit
  # to the head branch of the pull request,
  # use github.event.pull_request.head.sha instead.
  # Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      # no need to specify the ref, the GITHUB_REF of pull request event is the PR merge branch.
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    - name: Setup Jekyll environment
      uses: ./.github/actions/setup-jekyll-env
    - name: Write git info to site data
      uses: ./.github/actions/git-info
      with:
        target_file: _data/git.json
    - name: Build jekyll website
      env:
        JEKYLL_ENV: production
      run: |
        bundle exec jekyll build --trace
