
name: 'CI'

on:
  # Note that GITHUB_SHA for this event is the last merge commit of the pull
  # request merge branch. If you want to get the commit ID for the last commit
  # to the head branch of the pull request,
  # use github.event.pull_request.head.sha instead.
  # Docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, synchronize, reopened]
    branches-ignore:
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-24.04
    environment:
      name: CI
      url: ${{ steps.deploy_to_vercel.outputs.preview-url }}
    steps:
    - uses: actions/checkout@v4
      # no need to specify the ref, the GITHUB_REF of pull request event is the PR merge branch.
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

    # Prepare environment
    - name: Setup Jekyll environment
      uses: ./.github/actions/setup-jekyll-env
    - name: Setup Node environment
      uses: ./.github/actions/setup-nodejs
      with:
        node-version-file: .nvmrc

    # Perform CI checks
    - name: CI checks
      uses: ./.github/actions/ci-checks

    # Build Jekyll website to check for possible build errors
    - name: Build jekyll website
      run: bundle exec rake release

    # Write git info to site data as file for Vercel deploy
    - name: Write git info to site data
      uses: ./.github/actions/git-info
      with:
        target_file: _data/git.json

    # Get current REF to set a non-empty, URL-compliant,
    # and non-prod alias for Vercel deploy.
    - name: Get current ref
      id: get_current_ref
      uses: ./.github/actions/get-current-ref
    - name: Get deployment info
      id: get_deployment_info
      uses: ./.github/actions/get-deployment-info
      with:
        ref: ${{ steps.get_current_ref.outputs.ref }}

    # Perform a Vercel deploy, to check for ability to build on Vercel.
    # This should always perform a preview deploy.
    - name: Deploy on Vercel
      id: deploy_to_vercel
      uses: amondnet/vercel-action@v25.2.0
      # because dependabot[bot] is blocked from accessing secrets and writable tokens
      if: github.actor != 'dependabot[bot]'
      with:
        # analytics env vars are set on Vercel bc build happens there!
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # PR won't release to production, so no vercel-args (defaults to preview)
        vercel-args:  ''
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        alias-domains: |
          ${{ steps.get_deployment_info.outputs.vercel_alias }}
