# deploy fpira.com using GitHub Actions

name: 'deploy on vercel'

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - '.github/**'
      - '_jekyll_ignore/**'
      - README.md
      - '.gitignore'
      - '_drafts'
      - 'repo_utils/**'
      - '.vscode'
      - '.vercelignore'
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '45 8 * * *'
  workflow_dispatch:
    inputs:
      target_ref:
        description: "branch or ref to checkout to"
        required: false
        default: ''

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    outputs:
      RUN_BUILD: ${{ steps.check_new_posts.outputs.RUN_BUILD }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.target_ref }}
      - name: Check for new blog posts
        id: check_new_posts
        shell: bash
        run: |
          # if run on schedule, check for new posts
          if [ ${GITHUB_EVENT_NAME} = 'schedule' ]; then
            if [ $(ls -1 _posts | grep $(date '+%Y-%m-%d')) ]; then
              echo "New posts found with today date"
              echo "::set-output name=RUN_BUILD::true"
            else
              echo "No new posts to publish with today date."
              echo "::set-output name=RUN_BUILD::false"
            fi
          else
            echo "No checks to perform, about to run build..."
            echo "::set-output name=RUN_BUILD::true"
          fi
  build:
    name: Deploy on vercel
    runs-on: ubuntu-20.04
    needs: [checks]
    if: contains(needs.checks.outputs.RUN_BUILD, 'true')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.target_ref }}
    - name: Extract branch name
      id: extract_branch_name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    - name: Deploy to vercel (--prod)
      uses: amondnet/vercel-action@v20
      # weird 'if' syntax due to issue: https://github.com/actions/runner/issues/1173
      if: github.ref == format('refs/heads/{0}', 'main')
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    - name: Deploy to vercel (test)
      uses: amondnet/vercel-action@v20
      # weird 'if' syntax due to issue: https://github.com/actions/runner/issues/1173
      if: github.ref != format('refs/heads/{0}', 'main')
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        vercel-args: ''
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
    - name: Send Push Notification
      uses: fjogeleit/http-request-action@master
      if: always()
      with:
        url: ${{ secrets.NOTIFICATION_WEBHOOK_URI }}
        method: 'POST'
        data: '{ "value1": "[GitHub] pirafrank/fpiracom", "value2": "Build of fpira.com (ref ${{ github.ref }}) finished with status ${{job.status}}", "value3": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
