# deploy fpira.com using GitHub Actions

name: 'Notion to Jekyll'

on:
  workflow_dispatch:
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '15 8 * * *'

jobs:
  build:
    name: Notion to Jekyll
    runs-on: ubuntu-20.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
      with:
        # always checkout main branch
        ref: main
    - name: Get current ref (branch name or commit id)
      id: get_current_ref
      uses: ./.github/actions/get-current-ref
    - name: Notion to Jekyll
      uses: pirafrank/notion-to-jekyll@v1
      id: notion_to_jekyll
      with:
        notion-token: ${{ secrets.NOTION_TOKEN }}
        notion-database-id: ${{ vars.NOTION_TO_JEKYLL_DATABASE_ID }}
        publish-to-posts: ${{ vars.NOTION_TO_JEKYLL_PUBLISH_TO_POSTS }}
        relative-date: ${{ vars.NOTION_TO_JEKYLL_RELATIVE_DATE }}
        site-url: "https://fpira.com"
        assets-dir: "static/postimages"
        dry-run: ${{ vars.NOTION_TO_JEKYLL_DRY_RUN }}
    - name: Print variables
      env:
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        BRANCH: ${{ github.ref_name }}
        CHANGED: ${{ steps.notion_to_jekyll.outputs.changed }}
        DELETED: ${{ steps.notion_to_jekyll.outputs.deleted }}
        DRY_RUN: ${{ steps.notion_to_jekyll.outputs.dry-run }}
      run: |
        printf "\n******* workflow variables ********\n\n"
        echo "OWNER=$OWNER"
        echo "REPO=$REPO"
        echo "BRANCH=$BRANCH"
        printf "\n\n****** repository variables *******\n\n"
        echo NOTION_TO_JEKYLL_PUBLISH_TO_POSTS=${{ vars.NOTION_TO_JEKYLL_PUBLISH_TO_POSTS }}
        echo NOTION_TO_JEKYLL_RELATIVE_DATE=${{ vars.NOTION_TO_JEKYLL_RELATIVE_DATE }}
        echo NOTION_TO_JEKYLL_DRY_RUN=${{ vars.NOTION_TO_JEKYLL_DRY_RUN }}
        echo RUN_COMMIT_CHANGES=${{ vars.RUN_COMMIT_CHANGES }}
        printf "\n\n***** Notion to Jekyll output *****\n\n"
        echo "CHANGED=$CHANGED"
        echo "DELETED=$DELETED"
        echo "DRY_RUN=$DRY_RUN"
    - name: Generate commit message
      id: generate_commit_message
      run: |
        today=$(date +"%Y-%m-%d %H:%M:%S")
        export MESSAGE="Scheduled automatic update from Notion @ ${today}"
        echo "Commit message: ${MESSAGE}"
        echo "message=${MESSAGE}" >> $GITHUB_OUTPUT
    - name: Commit changes
      id: commit_changes
      uses: pirafrank/github-graphql-client@v1
      if: ${{ vars.RUN_COMMIT_CHANGES == 'true' && vars.NOTION_TO_JEKYLL_DRY_RUN != 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "commit --owner=${{ github.repository_owner }} --repo=${{ github.event.repository.name }} --branch=${{ github.ref_name }} --commitMessage=${{ steps.generate_commit_message.outputs.message }} --changed ${{ steps.notion_to_jekyll.outputs.changed }} --deleted ${{ steps.notion_to_jekyll.outputs.deleted }}"
    - name: Print output of commit changes step
      if: ${{ vars.RUN_COMMIT_CHANGES == 'true' }}
      run: |
        echo "${{ steps.commit_changes.outputs.commitUrl }}"
