# deploy fpira.com using GitHub Actions

name: 'Notion to Jekyll'

on:
  workflow_dispatch:
  # schedule is in UTC using cron syntax
  schedule:
    - cron: '15 8 * * *'

permissions:
  contents: write

jobs:
  notion-to-jekyll:
    name: Notion to Jekyll
    runs-on: ubuntu-24.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v7
      with:
        # always checkout main branch
        ref: main
    - name: Notion to Jekyll
      id: notion_to_jekyll
      uses: ./.github/actions/notion-to-jekyll
      with:
        notion-token: ${{ secrets.NOTION_TOKEN }}
        notion-data-source-id: ${{ vars.NOTION_TO_JEKYLL_DATA_SOURCE_ID }}
        publish-to-posts: ${{ vars.NOTION_TO_JEKYLL_PUBLISH_TO_POSTS }}
        relative-date: ${{ vars.NOTION_TO_JEKYLL_RELATIVE_DATE }}
        assets-dir: "static/postimages"
        dry-run: ${{ vars.NOTION_TO_JEKYLL_DRY_RUN }}
        run-commit-changes: ${{ vars.RUN_COMMIT_CHANGES }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Send Build Push Notification
      uses: fjogeleit/http-request-action@v2
      with:
        url: ${{ secrets.NOTIFICATION_WEBHOOK_URI }}
        method: 'POST'
        data: '{ "value1": "[GitHub] pirafrank/fpiracom", "value2": "Notion-to-Jekyll run (ref ${{ needs.checks.outputs.REF_NAME }}) finished with status ${{ job.status }}.<br><br><b>SUCCEEDED</b><br>${{ steps.notion_to_jekyll.outputs.notification_succeeded }}<br><b>FAILED</b><br>${{ steps.notion_to_jekyll.outputs.notification_failed }}<br>", "value3": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
