# deploy fpira.com using GitHub Actions

name: 'Test pipeline'

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: "branch or ref to checkout to"
        required: false
        default: ''

jobs:
  build:
    name: Test run
    runs-on: ubuntu-20.04
    steps:
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_ref }}
    - name: Get current ref (branch name or commit id)
      id: get_current_ref
      uses: ./.github/actions/get-current-ref
    - name: Get vercel args
      id: get_vercel_args
      shell: bash
      run: |
        if [ ${{ steps.get_current_ref.outputs.ref }} == 'main' ]; then
          echo "VERCEL_ARGS=$(echo '--prod')" >> $GITHUB_OUTPUT
        else
          echo "VERCEL_ARGS=$(echo '')" >> $GITHUB_OUTPUT
        fi
    - name: Write git info to site data
      uses: ./.github/actions/git-info
      with:
        target_file: _data/git.json
